language: node_js
node_js:
  - 12.16.1
services:
  - docker

before_install:
  - docker build -t piotrk84/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true piotrk84/docker-react npm run test
# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: docker-react
#   env: DockerReact-env
#   bucket_name: elasticbeanstalk-us-east-2-533489334743
#   bucket_path: docker-reacts
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master
