language: node_js
node_js:
  - 12.16.1
services:
  - docker

before_install:
  - docker build -t piotrk84/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true piotrk84/docker-react npm run test
